### PR TITLE
Added icons for home, add and all, added night and light theme support

### PR DESCRIPTION
**Pull request by bhaskarblur**
Hello there, i hope you're doing good.
I've made some good improvements to the UI by adding icons for home, add and all, improving the theme support for both light and night so now app supports both theme, changed the primary color to green for button.1

I can redesign the app to something very crazy that you willl love, but since i dont know your goal for this app, i didn't do much. I've improved the UI Designs in many open source mobile apps.

Please review and accept my PR. Thanks

### CODE REVIEW

**Comment by bhaskarblur** [comment]
@neeldoshii Please review this. Thanks

**Comment by neeldoshii** [comment]
Hello, 
Thank you for contributing really appreciated. I would like to have a screenshot of both night & day in the PR description. Sorry it's my fault PR template is not yet setup for this repo.

Can you provide any good color scheme for the app I am open for your opinion.

Currently this app is very basic would like to make something like this and add gamification to it 

https://play.google.com/store/apps/details?id=cc.forestapp
https://play.google.com/store/apps/details?id=com.toggl.giskard

Check this, our end goal is to have this and make it open source at the same time, we just want to eliminate procrastination and track the time of the task done.

Do you have any questions you can reach out to me at x(twitter), email, linkedin or comment here too if you want. 

Thanks

**Comment by bhaskarblur** [comment]
Screenshot_20231002_141523
Screenshot_20231002_141556

Here are the Screenshots

As for color scheme, i would suggest a mild green color scheme that would promote tasks and energy and eliminate procrastination, We would have think of the concept properly and then make features and make their design.
If you can list some features you want, i can come up with a design for them.

**Comment by neeldoshii** [comment]
Looks good!!!
I am extremely sorry for late PR. Thank you for your time and efforts @bhaskarblur while raising this PR. I am merging the PR.

**Comment by neeldoshii** [comment]
> As for color scheme, i would suggest a mild green color scheme that would promote tasks and energy and eliminate procrastination, We would have think of the concept properly and then make features and make their design. If you can list some features you want, i can come up with a design for them.

Color scheme looks good. Well, I started this project as an hobby/project while learning development which you guys might have seen by the ugly code base. But thankfully this project gaved me recognition in interview and was able to crack and land an internship. 

I feel the data should be stored on Room as when user is offline he can use the app but as he's on internet or when user has internet his data should be posted towards server for saving of tasks, visualization of tasks. I do want to add gamification so a graph of things will be perfect. 

Do you think firebase or other backend will be useful. @bhaskarblur @TharunBalaji2004 

Open for suggestions.

I would like to clone the concept of this app 
https://play.google.com/store/apps/details?id=cc.forestapp

We can add money rewards for completion of tasks in later phases, which I will explain

**Comment by bhaskarblur** [comment]
Hi. We can adopt a hybrid model of offline and online.
Cache things to local room db when online and use them later when online.

As for making data request changes when offline, queue the request to room dB and when connection active make the request, we can either make a room dB for it queue it on background service which checks when internet is connected.

PS: Congrats on landing internship 👏

**Comment by neeldoshii** [comment]
> We can adopt a hybrid model of offline and online.
> Cache things to local room db when online and use them later when online.
> 

Thank you for contributions. This will increase a lot of performance. 
What do you think will firebase be best as of now?

**Comment by bhaskarblur** [comment]
Firebase will be a pretty good backend as for now,
If a dedicated backend is needed on Node js , i am capable to develop that as well , i am a backend developer too.
But going with Firebase will be my suggestion.

**Comment by TharunBalaji2004** [comment]
> Hi. We can adopt a hybrid model of offline and online. Cache things to local room db when online and use them later when online.
> 
> As for making data request changes when offline, queue the request to room dB and when connection active make the request, we can either make a room dB for it queue it on background service which checks when internet is connected.
> 
> PS: Congrats on landing internship 👏

Yeah as @bhaskarblur said, we can adopt a hybrid model integrated with ROOM and Firebase. Also firebase would be a pretty good option, setting up and updating data can be performed much more easier.

**Comment by neeldoshii** [comment]
@bhaskarblur @TharunBalaji2004, Cool let's go with the firebase approach. Suggest me a proper way to setup firebase so others can also contribute over it and be on the same page?

**Comment by bhaskarblur** [comment]
Hi you should go ahead with setting up firebase for local repo and don't push it to git,
each contributor needs to setup their own firebase project along with the firebase requirements in the project in order to contribute properly as well as maintaining security.

**Comment by TharunBalaji2004** [comment]
As @bhaskarblur mentioned, we can allow contributors to setup their own firebase project and DB. Moreover, we can design schema or specify the directory structure which should be done in firebase. 

When merging the PR, maintainer can replace the credentials in firebase-config file with main DB

**Pull request merged**
