### PR TITLE
Fixed Navigation Back in Task Execute Screen - Issue (#6)

### PR DESCRIPTION
**Pull request by TharunBalaji2004**

### CODE REVIEW

**Review by TharunBalaji2004 — COMMENTED** [review]
Deleted .idea cache files

**Comment by TharunBalaji2004** [comment]
Hey @neeldoshii , can you tag the PR as hacktoberfest-accepted 😊

**Comment by neeldoshii** [comment]
Thank you for contributing. Will check your PR and merge it.

**Comment by neeldoshii** [comment]
Looks good merging the PR. Next Time please write

1. The description of fix
2. Add Screenshots/Video if applicable.
3. Steps to reproduce the bug for testing

**Pull request merged**
